### ISSUE TITLE
Create SEO checklist template

### ISSUE THREAD

**Issue by kuliebiakin** [innocode-digital/wp-theme-skeleton#2]
Use https://github.com/marcobiedermann/search-engine-optimization and https://github.com/douglasanro/wordpress-seo-checklist as base.

**Comment by JonRagnarSteg** [comment]
- [ ] Set internal search resultpage to noindex
- [ ] Allow moz.com to access site before launch so that we can check technical SEO quality

**Comment by kuliebiakin** [comment]
Template is updated to:

### General

- [ ] Stage site **is not** indexed (use site:my.stage.site.com to check)
- [ ] Production site **is not** indexed **before** launch
- [ ] Production site **is** indexed **after** launch
- [ ] Domains w/ _www_ and w/o _www_ are added but only one is used as primary
- [ ] Site domain is set to _live_ value in database after launch
- [ ] Site domain is set **only** to _www_ or _non-www_ value in database
- [ ] Use permalink structure with %postname%
- [ ] 404 page is added and styled
- [ ] HTML is valid
- [ ] Site is mobile friendly (use https://search.google.com/test/mobile-friendly)
- [ ] Check structured data at least on main pages (use https://search.google.com/structured-data/testing-tool)
- [ ] It's possible to set Google Analytics depending on environment
- [ ] WordPress SEO plugin is activated (in priority is Yoast, also possible to use SEOPress etc.)

### Resources

- [ ] Only fonts that are used are loaded with only needed language and characters set
- [ ] Correct image formats are used
- [ ] Correct image sizes are used
- [ ] Responsive images are used

### Content

- [ ] H1 tag is used only once per page and users can not add more from admin panel
- [ ] Meta description is used
- [ ] All external links are opening in new tab or window
- [ ] No duplicate content
- [ ] Images have _alt_ attribute **with** value
- [ ] Use WAI-Aria tags to help machines understand your code, if needed

**Comment by JonRagnarSteg** [comment]
> * [ ]  Set internal search resultpage to noindex
> * [ ]  Allow moz.com to access site before launch so that we can check technical SEO quality

Could you add these to the list?

**Comment by kuliebiakin** [comment]
This "Set internal search resultpage to noindex" is added in General (in 1, 2 and 3).
We do not block moz.com by default, where did you have such issues?

**Comment by JonRagnarSteg** [comment]
MOZ never works before a site is launched. I dont know how to fix this, but I hope someone in the team knows. Maybe we could test it on a site - ie a stage site or a site not yet launched?

**Comment by kuliebiakin** [comment]
So, it probably does not work on stage because stage has noindex.
Can you give me an example of site (url) which you tried to use with moz.com and it did not work?

**Comment by JonRagnarSteg** [comment]
Well teknologiradet2.prod.pingbull02.com and newscancook2.prod.pingbull02.com, but they are not there anymore. Can you provide me with a url we can test on? I can set up a new Moz campaign to run.

**Comment by JonRagnarSteg** [comment]
On the "header tags used" - can we specify H1. That is the most important one for SEO.

**Comment by JonRagnarSteg** [comment]
And:
-All pages need to contain canonical tags
-URL should not exceed 75 characters - we can effect this by controlling length of category names - not use dates in URLs ie.

**Comment by kuliebiakin** [comment]
All sites with urls like *.prod.pingbull02.com should be noindex as well because it's not "live" domains and it's added to checklist and due to this moz.com can not index it.

**Comment by kuliebiakin** [comment]
About H1 - it was already added, please check section **Content** -> 1.

**Comment by kuliebiakin** [comment]
> -All pages need to contain canonical tags
-URL should not exceed 75 characters - we can effect this by controlling length of category names - not use dates in URLs ie.

This is covered by Yoast.

**Comment by JonRagnarSteg** [comment]
> > -All pages need to contain canonical tags
> > -URL should not exceed 75 characters - we can effect this by controlling length of category names - not use dates in URLs ie.
> 
> This is covered by Yoast.

Ie Eksportkreditt has Yoast but still lots of too long url´s since they have date in urls. So in addition to Yoast we need to make sure URL are well set up.

**Comment by kuliebiakin** [comment]
It's a content issue not technical and should be fixed by editors, I think, because they can modify and control slugs.

**Comment by JonRagnarSteg** [comment]
I understand that, but still we should have a standard setup that we choose. The client does not always know how to do it.

Do you think the content in this issue now is ready to format and migrate to template?

**Comment by kuliebiakin** [comment]
Permalink structure depends on project requirements, so I think we should not include it in this template.

All content of list from this issue was already migrated to template.
